apiVersion: v1
kind: Service
metadata:
  name: spark-ui-master-service
spec:
  type: NodePort
  selector:
    component: spark-master  # Asegúrate de que esto coincida con las etiquetas de tus pods de Spark
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Elige un puerto en el rango 30000-32767 que no esté en uso
