apiVersion: v1
kind: Service
metadata:
  name: spark-ui-service
spec:
  type: NodePort
  selector:
    component: spark-master  # Asegúrate de que esto coincida con las etiquetas de tus pods de Spark
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 30040  # Elige un puerto en el rango 30000-32767 que no esté en uso
