kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: spark:3.5.0
          command: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker" ]
          args: [ "spark://spark-master:7077" ]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 1000m